/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const AiModel = React.memo(function AiModel(props) {
  // Use React.memo for performance optimization
  const modelRef = useRef();

  // Load the planet model
  const { scene } = useGLTF("/models/ai.glb");

  // Float animation
  useFrame((state) => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.005;
      modelRef.current.position.y =
        0 + Math.sin(state.clock.elapsedTime) * 0.25;
    }
  });

  return (
    <primitive
      ref={modelRef}
      object={scene}
      {...props}
      scale={[1, 1, 1]}
      position={[0, 0, 0]}
      rotation={[0, 9, 0]}
    />
  );
});

export default AiModel;

// Preload model for performance
useGLTF.preload("/models/ai.glb");
