/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const CommunityModel = React.memo(function CommunityModel(props) {
  // Use React.memo for performance optimization
  const modelRef = useRef();

  // Load the planet model
  const { scene } = useGLTF("/models/Community.glb");

  // Float animation
  useFrame((state) => {
    if (modelRef.current) {
      // modelRef.current.rotation.y += 0;
      modelRef.current.position.y =
        0.8 + Math.sin(state.clock.elapsedTime) * 0.25;
    }
  });

  return (
    <primitive
      ref={modelRef}
      object={scene}
      {...props}
      scale={[0.5, 0.5, 0.5]}
      position={[0, 0, 0]}
      rotation={[0, 4, 0]}
    />
  );
});

export default CommunityModel;

// Preload model for performance
useGLTF.preload("/models/Community.glb");
